---
title: "前瞻型临床研究的三表一图"
author: ZERO
date: '2020-09-16'
slug: qianzhanxing-linchuang-yanjiu-sanbiao-yitu.en-us
categories:
  - data science
tags:
  - Clinical
keywords:
  - tech
---


研究前只需思考一个问题——立意，即**找到与患者生存相关的临床变量**, 这个变量可以是检验指标，影像学特征，亦可以是血液中的某种分子，如DNA，RNA或蛋白质等等。

发表这种前瞻性临床研究的文章，一般主要包含收集数据、处理数据和撰写文章三大部分

## 第一部分：收集数据

1. 样本量：越大越好，对于仅仅有临床数据的文章来说，绝对是样本量越大越好，数据中心越多越好，**至少要几百人**，这样做出来的数据结果可信度会更好一些。
2. 基线资料类型：**适量就好，结合相关文章报道确定具体类型**。


比如胰腺癌方向，因此在基线资料方面除了常见的年龄、性别、TNM分期、临床分期、病理分级、家族肿瘤史、生存时间和生存状态之外，还录入了糖尿病病史、慢性胰腺炎病史以及肿瘤部位等。大家可以根据自己的学科类型来确定，但有一个原则要遵守，即数据要全。

此外，最重要的是要选定一个**目标临床变量，这个是你这个文章的亮点**，是什么因素和患者的预后相关，例如以上数据可以做**糖尿病既往病史**和胰腺癌患者生存的相关性或者**CA199的表达量**和胰腺癌患者预后生存的相关性

对于数据分析来说，**将数据转换为二分类变量**，即0/1，或者1/2, 更有临床意义或者更利于解释结果。但是对于一些特殊的肿瘤，像乳腺癌，肠癌等T分期比较均匀的，也可以用1，2，3和4多类来表示。例如：年龄以60为分界线，1为≥60，2为<60，


## 第二部分：处理数据
接下来就可以进行数据分析，制作“三表一图”了。“三表”是**Table 1**，**Spearman相关性分析表**，**单因素/多因素COX回归表**，“一图”是**生存分析图**


比如进行分析的立意是**CA199的表达量和胰腺癌患者预后生存的相关性**。

+ Table 1
+ Spearman相关性研究表
+ 单因素、多因素COX回归分析表

做完单因素分析后，我们需要选几个变量进行多因素分析，最好是P值有统计学意义，这里可以将P值的范围扩大到0.1或0.5，对于一些与患者生存预后明显相关的因素（如临床分期，病理分级等），即便是P值没有意义也应该纳入多因素分析中

+ 生存分析图

## 第三部分：撰写文章 

文章撰写对于第一次写文章的小白来说是完全没有头绪。问师兄师姐，他们一般会说多读文献，就会了。他们说的对吗？对也不对，确实要多读文章，可是关键的怎么读并没有告诉你。

而对于论文的撰写，我们除了多读文章，首先要找到一篇相似类型的文章，然后进行模仿。我导师曾告诉我要**善于模仿，在模仿中进步，在模仿中创新**。对于一篇论文我们要知道每一部分写什么，也就是文章的框架，有了我们要模仿文章的框架然后填上自己的内容，这就是自己的文章了。这不是抄袭，是学习，也是创新。

 
## 小结 
“三表一图”是许多基础实验文章的临床部分内容，对于一些可以进行实验验证的分子最好还是继续做下细胞动物实验。但是如果分子表型并没有显著差异或者临床特征不能进行实验验证的，仅仅靠临床部分，也发表一篇独立的SCI文章的。
